let requestObj = {
	getMailOrderList:{
		url:'/yoursender/api/mailOrder/getMailOrderList',
		type:'GET'
		
	},
	addLogisticOrder:{
		url:'/yoursender/api/mailOrder/addLogisticOrder',
		type:'POST'
	},
	wechatLogin:{
		url:'/yoursender/api/wechat/login',
		type:'GET',
		otherGet:true
	},
	mailInfo:{
		url:'/yoursender/api/mailOrder/mailInfo',
		type:'GET',
		otherGet:true
	},
	getRoutes:{
		url:'/yoursender/api/mailOrder/getRoutes',
		type:'GET'
	},
	infoByReceiptsNo:{
		url:'/yoursender/api/mailOrder/infoByReceiptsNo',
		type:'GET',
		otherGet:true
	},
	testParams:{
		url:'/yoursender/api/wechat/testParams',
		type:'POST'
	},
	payOrder:{
		url:'/yoursender/api/wechat/payOrder',
		type:'POST'
	},
	getFreight:{
		url:'/yoursender/api/mailOrder/getFreight',
		type:'GET',
	},
	orderCancel:{
		url:'/yoursender/api/mailOrder/orderCancel',
		type:'GET',
		otherGet:true
	},
	getNotification:{
		url:'/yoursender/api/mailOrder/getNotification',
		type:'GET'
	}
}
export default requestObj;